$primary = rgb(ffb68f)
$surface = rgb(18120f)
$secondary = rgb(e6beab)
$error = rgb(ffb4ab)
$tertiary = rgb(cec991)
$surface_lowest = rgb(120d0a)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
