color0 #1a110f
color1 #ffb4ab
color2 #ffb4a3
color3 #dbc58c
color4 #ffdad2
color5 #ffdad2
color6 #e7bdb4
color7 #f1dfdb
color8 #423734
color9 #ffb4ab
color10 #ffb4a3
color11 #dbc58c
color12 #ffdad2
color13 #ffdad2
color14 #e7bdb4
color15 #f1dfdb
background #1a110f
selection_foreground #ffb4a3
cursor #f1dfdb
cursor_text_color #534340
foreground #f1dfdb
selection_background #561f12
active_border_color #ffb4a3
inactive_border_color #ffb4a3

active_tab_foreground   #621000
active_tab_background   #ffb4a3
inactive_tab_foreground #dfc0b8
inactive_tab_background #291d1a
cursor_trail_color      #dfc0b8
