color0 #18120f
color1 #ffb4ab
color2 #ffb68f
color3 #e6beab
color4 #cec991
color5 #ffb68f
color6 #e6beab
color7 #ece0db
color8 #9f8d84
color9 #ffb4ab
color10 #ffb68f
color11 #e6beab
color12 #cec991
color13 #ffb68f
color14 #e6beab
color15 #ece0db

cursor                #ece0db
cursor_text_color     #18120f
background            #18120f
foreground            #ece0db
selection_foreground  #d7c2b9
selection_background  #52443d
active_border_color   #ffb68f
inactive_border_color #52443d
url_color             #ffb68f

active_tab_foreground   #542100
active_tab_background   #ffb68f
inactive_tab_foreground #d7c2b9
inactive_tab_background #52443d
cursor_trail_color      #d7c2b9
