color0 #181211
color1 #ffb4ab
color2 #ffb4a2
color3 #e7bdb3
color4 #dac58c
color5 #ffb4a2
color6 #e7bdb3
color7 #ede0dd
color8 #a08c88
color9 #ffb4ab
color10 #ffb4a2
color11 #e7bdb3
color12 #dac58c
color13 #ffb4a2
color14 #e7bdb3
color15 #ede0dd

cursor                #ede0dd
cursor_text_color     #181211
background            #181211
foreground            #ede0dd
selection_foreground  #d8c2bd
selection_background  #534340
active_border_color   #ffb4a2
inactive_border_color #534340
url_color             #ffb4a2

active_tab_foreground   #5e1605
active_tab_background   #ffb4a2
inactive_tab_foreground #d8c2bd
inactive_tab_background #534340
cursor_trail_color      #d8c2bd
