# Matteblack theme for Hyprland
# Upstream: github.com/tahayvr/matteblack.nvim

$primary        = rgb(FBBF24)   # normal yellow 
$surface        = rgb(121212)   # background
$secondary      = rgb(F1CB42)   # bright yellow — grouped windows
$error          = rgb(B91C1C)   # normal red
$tertiary       = rgb(3B82F6)   # normal blue
$surface_lowest = rgb(0d0d0d)   # darker than background

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
