# See: /usr/share/doc/mpd/mpdconf.example
playlist_directory  "~/.config/playlist_mpd"
db_file            "~/.config/mpd/database"
log_file	   "~/.config/mpd/mpd.log"
music_directory    "~/Música/"
pid_file           "~/.config/mpd/mpd.pid"
state_file         "~/.config/mpd/mpdstate"
audio_output {
        type            "pulse"
        name            "pulse audio"
}
audio_output {
    type		"fifo"
    name		"FIFO"
    path		"/tmp/mpd.fifo"
    format		"44100:16:2"
}

playlist_plugin {
    name "m3u"
    enabled "true"
}
