# Colors (Noctalia)

[colors.bright]
black = '#423734'
blue = '#ffdad2'
cyan = '#e7bdb4'
green = '#ffb4a3'
magenta = '#ffdad2'
red = '#ffb4ab'
white = '#f1dfdb'
yellow = '#dbc58c'

[colors.cursor]
cursor = '#f1dfdb'
text = '#534340'

[colors.normal]
black = '#1a110f'
blue = '#ffdad2'
cyan = '#e7bdb4'
green = '#ffb4a3'
magenta = '#ffdad2'
red = '#ffb4ab'
white = '#f1dfdb'
yellow = '#dbc58c'

[colors.primary]
background = '#1a110f'
foreground = '#f1dfdb'

[colors.selection]
background = '#561f12'
text = '#ffb4a3'
