import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/config/keybinds.toml",
  "~/.config/alacritty/config/fontconfig.toml"
]

[window]
startup_mode = "Maximized"
dynamic_title = true
