
[window]
startup_mode = "Maximized"
dynamic_title = true

[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/themes/moonfly.toml",
  "~/.config/alacritty/config/keybinds.toml",
  "~/.config/alacritty/config/fontconfig.toml"
]
